Bread.create(name: "Pumpernickel", flavor: "Pumpernickelly", price: 10)
Bread.create(name: "Whole Wheat", flavor: "Cardboardy", price: 20)
Bread.create(name: "Peasant Bread", flavor: "Delicious", price: 15)
Bread.create(name: "Rye", flavor: "of the Tiger", price: 5)

Bakery.create(name: "Breads Bakery", address: "Union Square")
Bakery.create(name: "Levain Bakery", address: "Upper West Side")
Bakery.create(name: "Dough", address: "Bedford-Stuyvesant")
Bakery.create(name: "The French Workshop", address: "Bayside")
Bakery.create(name: "Luckybird Bakery", address: "Williamsburg")
